blank_issues_enabled: true
contact_links:
  - name: ❓ Q&A Technical Support Channel
    url: https://discord.gg/jgH5wkwCtf
    about: For quick questions or technical troubleshooting, please ask them on our dedicated Discord channel.
